# Generated by Django 2.2.6 on 2020-08-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioimages_more_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioimages',
            name='more_image',
        ),
        migrations.AddField(
            model_name='portfolioimages',
            name='more_image',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.subImages'),
        ),
    ]
