# Generated by Django 2.2.6 on 2020-08-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200804_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimages',
            name='title',
            field=models.CharField(blank=True, default='X', max_length=500, null=True),
        ),
    ]
